Trans of Id: 101 and push test
summerkirakira/ScLocalizationTools pull request #25
Opened 2022-10-24 15:03 UTC by Number238

2022-10-24 15:07 UTC, summerkirakira requested changes
不要修改原有的内容，把汉化填到Chinese开头的字段里

2022-10-25 11:37 UTC, JASACOMB commented
> 不要修改原有的内容，把汉化填到Chinese开头的字段里

不是我改的）

2022-10-25 12:04 UTC, Number238 commented
是我改的哟
________________________________
发件人: JASACOMB ***@***.***>
发送时间: 2022年10月25日 4:37
收件人: summerkirakira/ScLocalizationTools ***@***.***>
抄送: Number238 ***@***.***>; Author ***@***.***>
主题: Re: [summerkirakira/ScLocalizationTools] Trans of Id: 101 and push test (PR #25)


不要修改原有的内容，把汉化填到Chinese开头的字段里

不是我改的）

―
Reply to this email directly, view it on GitHub<https://github.com/summerkirakira/ScLocalizationTools/pull/25#issuecomment-1290410757>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOUTJRFKRVNRWLBCY4UAHMLWE7BBBANCNFSM6AAAAAARNCHSPA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-25 17:38 UTC, JASACOMB commented
那你快改回来（

2022-10-25 19:01 UTC, closed without merging